### PR TITLE
RL4J - Fix / workaround for cases when Random.getFloat() returns 1.0

### PR DESCRIPTION
**Pull request by aboulang2002**
## What changes were proposed in this pull request?

`Nd4j.EPS_THRESHOLD` (or a user supplied value) is substracted from `Random.getFloat()` in the policies to get closer to the convention of [0, 1)

See issue: https://github.com/eclipse/deeplearning4j/issues/8800

## How was this patch tested?

Unit tests & manual tests

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X] Created tests for any significant new code additions.
- [X] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by saudet** [comment]
From what I understand, that's actually a bug in ND4J. I'm not sure if we want to add workarounds like that... @treo ?

**Comment by treo** [comment]
@saudet yes. I consider this to be a bug in ND4J's random number generator. 

As a workaround, it would have been enough to change the `<` to `<=` here:
https://github.com/KonduitAI/deeplearning4j/blob/master/rl4j/rl4j-core/src/main/java/org/deeplearning4j/rl4j/policy/ACPolicy.java#L82

As we are drawing random numbers anyway, it only really changes the behavior for two edge cases:
1. When `rVal = 1.0`, it doesn't error out.
2. When `rVal = 0.0` and the probability for the first action also being exactly `0`, it will take that action, even though it has zero probability. 

The eps fix has both of those properties too but introduces quite a bit of additional code, even though we can honestly expect that no-one will ever actually set the eps value here. 

So if we want to implement a workaround for the bug, I guess going for the solution I suggest, is less effort over the long run.

**Comment by raver119** [comment]
Maybe lets just apply fix to rng, to make it [0, 1)?

**Comment by treo** [comment]
That would be the preferred solution :)

**Comment by aboulang2002** [comment]
I will abandon this PR and create another one with just the temporary workaround `<` to `<=` in ACPolicy.
That workaround is to be removed when the fix is made in Nd4j.

**Comment by raver119** [comment]
No need, tomorrow morning i’ll merge proper fix. it’s already in CI.

With best regards,
raver119
29 мая 2020 г., 22:53 +0300, Alexandre Boulanger <notifications@github.com>, писал:

**Pull request closed without merging**
