### PR TITLE
RL4J - Added Agent and Environment

### PR DESCRIPTION
**Pull request by aboulang2002**
## What changes were proposed in this pull request?

A PR introducing `Agent` and `Environment` in RL4J. Refactoring the legacy code is becoming increasingly difficult without breaking the code for existing users. Instead, new code will be added to RL4J and legacy code will be deprecated.

Environment:
 - Instead of `ActionSpace` and `ObservationSpace`, I wanted to do something similar to DataVec's schema. I'd like to be able to have metadata in this schema for example to help normalization or describe the data channel (describe it's the left audio channel or the right one for example)
 - `step()` now returns a StepResult that contains a Map<String, Object> (same thing for `reset()`). Maybe we should define a container class instead using directly a map.

I added a test environment (`CartpoleEnvironment`) in `org.deeplearning4j.rl4j.mdp` to help for the development and tests
 
Agent:
 - First iteration that can presently only play an episode with a pre-trained model.
 - The number of protected methods seems overkill but I plan to make the LearnerAgent extend Agent and it'll be much easier.

## How was this patch tested?

unit tests and manual tests

## Quick checklist

The following checklist helps ensure your PR is complete:

- [x] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [x] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [x] Created tests for any significant new code additions.
- [x] Relevant tests for your changes are passing.
- [ ] Javadoc
- [x] Headers

### CODE REVIEW

**Comment by aboulang2002** [comment]
I did not add the javadoc/headers because it'll bring this PR over 1000 lines. Should I add it in this PR or another one?
Also, the unit tests are using mokito, so I'll wait that PR #327 has been merged before changing the draft status.

**Comment by saudet** [comment]
@aboulang2002 Feel free to add the headers. We can argue it's boilerplate and not part of the LOC :)

**Comment by saudet** [comment]
@aboulang2002 We'll need to resolve the conflicts here as well...

**Comment by saudet** [comment]
@Bam4d It looks like @aboulang2002 is reverting your changes to the Policy interface. Are you OK with this?

**Comment by aboulang2002** [comment]
> It looks like @aboulang2002 is reverting your changes to the Policy interface. Are you OK with this?

I need `IPolicy` in `Agent` and I don't want Encodable in the new dev. So, I moved the constraint `O extends Encodable` in the methods of `Policy`.

**Review by saudet — APPROVED** [review]

**Pull request merged**
