### PR TITLE
Fixing python object for obtaining scalars

### PR DESCRIPTION
**Pull request by ShamsUlAzeem**
## What changes were proposed in this pull request?

This PR fixed issues for obtaining an INDArray from a numpy scalar.

## How was this patch tested?

Unit tests

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X] Created tests for any significant new code additions.
- [X] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by AlexDBlack** [comment]
I'm seeing a CI failure on this branch (linux x86_64 and cuda) in datavec-python - not sure yet if also happening on master or not...

```
[2020-03-18T23:45:16.251Z] Failed tests: 
[2020-03-18T23:45:16.251Z]   TestPythonExecutioner.testNDArrayNoCopy:241 expected:<[[    0.4078,    1.3354], 

[2020-03-18T23:45:16.251Z]  [    1.3251,    0.2249], 
[2020-03-18T23:45:16.251Z]  [    0.0439,    2.0523]]> but was:<[[    0.4078,    0.4078], 
[2020-03-18T23:45:16.251Z]  [    0.4078,    0.4078], 
[2020-03-18T23:45:16.252Z]  [    0.4078,    0.4078]]>
[2020-03-18T23:45:16.252Z] 
[2020-03-18T23:45:16.252Z] Tests run: 50, Failures: 1, Errors: 0, Skipped: 1
```

**Comment by AlexDBlack** [comment]
I tested master for datavec tests locally on my machine (linux x86_64) and it's fine, no test failures.
So that CI failure is probably introduced in this branch

**Comment by ShamsUlAzeem** [comment]
Seems like the updates to `toNumpy()` did that. Not sure why it only  happens in a certain OS. All of them failed in linux and the windows error seems like it's because of something else.

I've asked @farizrahman4u to look into this as well.

**Comment by ShamsUlAzeem** [comment]
@AlexDBlack @farizrahman4u I think the tests are passing now. I was using a wrong variable at some place. There are some other errors and build issues though but not with this PR afaik

**Comment by ShamsUlAzeem** [comment]
Okay the tests are fixed and visible here: https://jenkins.konduit.ai/blue/organizations/jenkins/konduitai%2Fdeeplearning4j/detail/PR-330/5/tests/

see the fixed section

**Comment by AlexDBlack** [comment]
Was seeing unrelated failure here - ignore for that merged to master (until fixed).
https://github.com/eclipse/deeplearning4j/issues/8802

I've merged master in to this branch, hopefully things should be passing on CI now

**Review by AlexDBlack — APPROVED** [review]

**Pull request merged**
