### PR TITLE
Add support for CUDA 11.0

### PR DESCRIPTION
**Pull request by saudet**
Updates JavaCPP, JavaCV, and all presets to 1.5.4-SNAPSHOT, which now support CUDA 11.

Deeplearning4j itself still needs to be updated for this to work though.

@raver119 Feel free to work on this branch

### CODE REVIEW

**Review by raver119 — DISMISSED** [review]

**Comment by raver119** [comment]
@saudet I can't build nd4j. Looks like macosx leaked into pom once again

```
[ERROR] Failed to execute goal on project nd4j-cuda-11.0-platform: Could not resolve dependencies for project org.nd4j:nd4j-cuda-11.0-platform:jar:1.0.0-SNAPSHOT: Could not find artifact org.bytedeco:cuda:jar:macosx-x86_64:11.0-8.0-1.5.4-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

**Comment by saudet** [comment]
@raver119 Fixed! Sorry about that

**Comment by raver119** [comment]
Cool, will try again now then.

**Comment by raver119** [comment]
So ye, I can can confirm: libnd4j/nd4j builds fine now in this branch, and all libnd4j/ND4J tests pass.

Once this branch merged, we'll add BFLOAT16/TF32 support in separate PRs.

**Review by raver119 — DISMISSED** [review]

**Comment by raver119** [comment]
@saudet any chance we could merge this?

**Comment by saudet** [comment]
> @saudet any chance we could merge this?

Anytime you want, but we should probably fix deeplearning4j-cuda first:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project deeplearning4j-cuda-11.0: Compilation failure: Compilation failure: 
[ERROR] /home/saudet/projects/konduit/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/main/java/org/deeplearning4j/cuda/convolution/CudnnConvolutionHelper.java:[259,53] cannot find symbol
[ERROR]   symbol:   variable CUDNN_CONVOLUTION_BWD_FILTER_NO_WORKSPACE
[ERROR]   location: class org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper
[ERROR] /home/saudet/projects/konduit/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/main/java/org/deeplearning4j/cuda/convolution/CudnnConvolutionHelper.java:[260,31] cannot find symbol
[ERROR]   symbol:   variable CUDNN_CONVOLUTION_BWD_FILTER_PREFER_FASTEST
[ERROR]   location: class org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper
[ERROR] /home/saudet/projects/konduit/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/main/java/org/deeplearning4j/cuda/convolution/CudnnConvolutionHelper.java:[265,53] cannot find symbol
[ERROR]   symbol:   variable CUDNN_CONVOLUTION_BWD_DATA_NO_WORKSPACE
[ERROR]   location: class org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper
[ERROR] /home/saudet/projects/konduit/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/main/java/org/deeplearning4j/cuda/convolution/CudnnConvolutionHelper.java:[266,31] cannot find symbol
[ERROR]   symbol:   variable CUDNN_CONVOLUTION_BWD_DATA_PREFER_FASTEST
[ERROR]   location: class org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper
[ERROR] /home/saudet/projects/konduit/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/main/java/org/deeplearning4j/cuda/convolution/CudnnConvolutionHelper.java:[467,31] cannot find symbol
[ERROR]   symbol:   variable CUDNN_CONVOLUTION_FWD_NO_WORKSPACE
[ERROR]   location: class org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper
[ERROR] /home/saudet/projects/konduit/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/main/java/org/deeplearning4j/cuda/convolution/CudnnConvolutionHelper.java:[467,68] cannot find symbol
[ERROR]   symbol:   variable CUDNN_CONVOLUTION_FWD_PREFER_FASTEST
[ERROR]   location: class org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper
[ERROR] -> [Help 1]
```

**Comment by raver119** [comment]
Aha, good point, I'll take a look.

@sshepel We also need to update CI for new cuDNN as well then.

**Comment by raver119** [comment]
I've updated API to match cuDNN 8.0, but:

1.  It's backward incompatible. We'll keep that in mind.
2.  I see some dl4j cudnn tests crashing. Need to check that out too.

**Comment by raver119** [comment]
By the looks of it, issue I'm facing here looks like cuDNN issue. It's "Invalid alignment" exception coming from device side from cuDNN filter backprop step.

We'll update C++ implementations of cuDNN helpers, and continue investigation from there.

**Comment by raver119** [comment]
So, turns out that our old workaround for Same padding mode doesn't work anymore, and causes troubles.

cc @AlexDBlack

**Comment by raver119** [comment]
Crash fixed. Turns out there's ninja requirement was added: eps array should be 128-bits aligned for certain cuDNN algos. 

@AlexDBlack I have one cuDNN test failure here: ValidateCudnnLSTM.validateImplMultiLayerTBPTT

**Comment by raver119** [comment]
Last failing test issue fixed.

@sshepel basically we're ready to merge, but it would be nice to see CI results first. Just to make sure everything works as intended.

**Comment by raver119** [comment]
@saudet can you take a look please:

```
Failed to execute goal on project nd4j-tests-tensorflow: Could not resolve dependencies for project org.nd4j:nd4j-tests-tensorflow:jar:1.0.0-SNAPSHOT: Could not find artifact org.bytedeco:tensorflow:jar:macosx-x86_64-gpu:1.15.3-1.5.4-SNAPSHOT in maven-public (https://packages.konduit.ai/repository/maven-public/) -> [Help 1]
```

**Comment by raver119** [comment]
@saudet thank you very much, macos issue solved. now there's some cryptic datavec-image exception:

```
[2020-07-10T04:42:35.622Z] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.4 sec <<< FAILURE! - in org.datavec.image.loader.TestImageLoader

[2020-07-10T04:42:35.622Z] testNCHW_NHWC(org.datavec.image.loader.TestImageLoader)  Time elapsed: 0.125 sec  <<< ERROR!

[2020-07-10T04:42:35.622Z] java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper

[2020-07-10T04:42:35.622Z] 	at org.datavec.image.loader.TestImageLoader.testNCHW_NHWC(TestImageLoader.java:226)

[2020-07-10T04:42:35.622Z] 

[2020-07-10T04:42:35.622Z] Running org.datavec.image.loader.TestNativeImageLoader

[2020-07-10T04:42:36.994Z] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.302 sec - in org.datavec.image.loader.TestNativeImageLoader

[2020-07-10T04:42:36.994Z] Running org.datavec.image.transform.TestImageTransform

[2020-07-10T04:42:37.251Z] Tests run: 14, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.426 sec - in org.datavec.image.transform.TestImageTransform

[2020-07-10T04:42:37.251Z] Running org.datavec.image.transform.JsonYamlTest

[2020-07-10T04:42:37.508Z] 0	ColorConversionTransform(conversionCode=50)

[2020-07-10T04:42:37.766Z] 1	CropImageTransform(cropTop=10, cropLeft=10, cropBottom=10, cropRight=10, x=0, y=0)

[2020-07-10T04:42:37.766Z] 2	EqualizeHistTransform(conversionCode=6, splitChannels=[])

[2020-07-10T04:42:37.766Z] 3	FlipImageTransform(flipMode=0, h=0, w=0, mode=0)

[2020-07-10T04:42:37.766Z] 4	ResizeImageTransform(newHeight=300, newWidth=300, srch=0, srcw=0)

[2020-07-10T04:42:37.766Z] 5	RotateImageTransform(centerx=0.0, centery=0.0, angle=30.0, scale=0.0, interMode=1, borderMode=0, borderValue=(0.0, 0.0, 0.0, 0.0), M=null)

[2020-07-10T04:42:37.766Z] 6	ScaleImageTransform(dx=3.0, dy=3.0, srch=0, h=0, srcw=0, w=0)

[2020-07-10T04:42:37.766Z] 7	WarpImageTransform(deltas=[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], interMode=1, borderMode=0, borderValue=(0.0, 0.0, 0.0, 0.0), M=null)

[2020-07-10T04:42:37.766Z] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.521 sec - in org.datavec.image.transform.JsonYamlTest

[2020-07-10T04:42:37.766Z] Running org.datavec.image.transform.ResizeImageTransformTest

[2020-07-10T04:42:37.766Z] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec - in org.datavec.image.transform.ResizeImageTransformTest

```

However, it's definitely not CUDA 11 related, since it's a failure from cpu backend.

So the last issue to solve will be windows-cuda tests execution issue. @sshepel any ideas what's wrong there?

**Comment by sshepel** [comment]
@raver119 exit code 127 says that something tool or exec bit is missing on Jenkins agent... Need to check CUDA 11 env dependencies once again.

**Pull request merged**
