### PR TITLE
Backwardly Compatible Builder patterns

### PR DESCRIPTION
**Pull request by Bam4d**
This is a backwardly compatible version of this PR: https://github.com/KonduitAI/deeplearning4j/pull/307

All existing 1.0.0-beta6 examples work against these changes

## What changes were proposed in this pull request?

Decoupled configuration of learning methods from implementations. This allowed
1) Better heirarchical configuration
2) Easier to add new configurations to new learners without duplicating code as interfaces and abstract parameters can be inherited where needed.

Decoupled configuration of RL Neural Nets from implementations. The idea for this is the same as above. Eventually we want to move to a much more plug-and-play system of defining neural networks seperately from the actual learning algorithms. This is a step towards doing that.

All configuration classes are implemented with builder patterns.
1) Many hyperparameters in RL algorithms are left at default values given by in state of the art papers.
2) setting hyperparameters is explicit and readable

## How was this patch tested?

Unit tests were refactored as part of the changes and they are all running and passing after. 
No new test cases were needed as functionality was not changed at all.

## Quick checklist

The following checklist helps ensure your PR is complete:

- [x] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [x] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [x] Created tests for any significant new code additions.
- [x] Relevant tests for your changes are passing.

### CODE REVIEW

**Review by saudet — DISMISSED** [review]
Please fix merge conflicts.

**Review by AlexDBlack — DISMISSED** [review]
A few small issues repeated in a number of places:
* missing copyright headers 
* No javadoc on a lot of config classes
* Missing access modified (should be private or protected, not default to package private)

otherwise this looks fine to me so far :+1:

**Comment by saudet** [comment]
I'm getting a bunch of errors when compiling the examples. How is this meant to preserved backward compatibility?

**Comment by Bam4d** [comment]
> I'm getting a bunch of errors when compiling the examples. How is this meant to preserved backward compatibility?

@saudet hmmm it appears all my changes went missing :/ Must have messed up a rebase or something

**Comment by Bam4d** [comment]
@saudet Thanks for pointing out the errors with the examples code. I'd lost a bunch of stuff during the rebase so had to re-add it. Now compiling and running fine against the konduit/master examples branch

**Comment by saudet** [comment]
Ok, thanks, it builds now, but I'm getting NPEs with Cartpole, A3CCartpole, A3CALE, etc, for example:
```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:293)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.NullPointerException
    at java.util.Objects.requireNonNull (Objects.java:203)
    at java.util.Arrays$ArrayList.<init> (Arrays.java:3813)
    at java.util.Arrays.asList (Arrays.java:3800)
    at org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense$Configuration.toNetworkConfiguration (DQNFactoryStdDense.java:118)
    at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteDense.<init> (QLearningDiscreteDense.java:75)
    at org.deeplearning4j.examples.rl4j.Cartpole.cartPole (Cartpole.java:84)
    at org.deeplearning4j.examples.rl4j.Cartpole.main (Cartpole.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:293)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by AlexDBlack** [comment]
@Bam4d Sorry, I should have clarified re: copyright headers
Any pre-existing classes that have been modified/refactored/renamed should be:
```
Copyright (c) 2015-2019 Skymind, Inc.
Copyright (c) 2020 Konduit K.K.
```
Any new classes (not based on old ones or from copy/paste etc) should be:
```
Copyright (c) 2020 Konduit K.K.
```

otherwise changes look fine.

**Review by saudet — CHANGES_REQUESTED** [review]
Please fix the NPEs!

**Comment by Bam4d** [comment]
@saudet fixed the NPEs and have all the examples except Toy, due to a different bug which is fixed in https://github.com/KonduitAI/deeplearning4j/pull/352

@AlexDBlack Have done the updates to the copyright headers. Let me know if those are the ones you want.

**Comment by AlexDBlack** [comment]
Thanks @Bam4d - looks good to me

**Comment by saudet** [comment]
@Bam4d All examples seem to work OK, but I'm getting this warning with A3CCartpole and A3CALE:
```
java.lang.ArithmeticException: / by zero
    at org.deeplearning4j.rl4j.learning.async.AsyncGlobal.run (AsyncGlobal.java:98)
```
Also, ALE is not outputting anything to the log anymore. Is this all intentional?

**Comment by Bam4d** [comment]
@saudet Have put the logging back to ALE, not sure why i commented it out. Good catch.

The divide by zero issue is something that is fixed in this PR: https://github.com/KonduitAI/deeplearning4j/pull/327

**Comment by saudet** [comment]
Thanks! With these latest changes though, a unit test started to fail:
```
Failed tests: 
  TransformProcessTest.when_preProcessIsCalled_expect_channelDataPreProcessedInSameOrder:131 expected:<1> but was:<2>
```
Can we revert whatever broke this, or fix the test if it's wrong, before merging this? @aboulang2002?

**Comment by saudet** [comment]
Moreover, the `stepCounter` doesn't seem to be working properly for A3C. Its value does increase in the `stat` file, but it doesn't increase in the `info` file. The training also doesn't stop after reaching `maxStep`. @Bam4d Please fix this before we merge!

**Comment by Bam4d** [comment]
> Thanks! With these latest changes though, a unit test started to fail:
> 
> ```
> Failed tests: 
>   TransformProcessTest.when_preProcessIsCalled_expect_channelDataPreProcessedInSameOrder:131 expected:<1> but was:<2>
> ```
> 
> Can we revert whatever broke this, or fix the test if it's wrong, before merging this? @aboulang2002?

This was caused by #352 and the test is now fixed. Not sure why the test passed or did not run on that branch though.

**Comment by Bam4d** [comment]
> Moreover, the `stepCounter` doesn't seem to be working properly for A3C. Its value does increase in the `stat` file, but it doesn't increase in the `info` file. The training also doesn't stop after reaching `maxStep`. @Bam4d Please fix this before we merge!

Thanks again for this feedback! I think I've fixed that now.

**Comment by aboulang2002** [comment]
> > Thanks! With these latest changes though, a unit test started to fail:
> > ```
> > Failed tests: 
> >   TransformProcessTest.when_preProcessIsCalled_expect_channelDataPreProcessedInSameOrder:131 expected:<1> but was:<2>
> > ```
> > 
> > 
> > Can we revert whatever broke this, or fix the test if it's wrong, before merging this? @aboulang2002?
> 
> This was caused by #352 and the test is now fixed. Not sure why the test passed or did not run on that branch though.

We need remember to fix that 2D or more shape requirement. But in the meantime, I guess it's acceptable.

**Review by saudet — APPROVED** [review]

**Pull request merged**
