### PR TITLE
python exec: remove numpy patching

### PR DESCRIPTION
**Pull request by farizrahman4u**

### CODE REVIEW

**Comment by agibsonccc** [comment]
@farizrahman4u if we get rid of this, are we going to have the same numpy problems in the new version? We can't just forget we had this problem.

**Comment by saudet** [comment]
If this doesn't have any undesired side effects, we can add the patch upstream here:
https://github.com/bytedeco/javacpp-presets/tree/master/numpy

**Comment by agibsonccc** [comment]
@farizrahman4u can you send the PR for javacpp? I like @saudet 's suggestion.

**Comment by farizrahman4u** [comment]
We dont need this patch anymore in the new python executioner.

**Comment by saudet** [comment]
> We dont need this patch anymore in the new python executioner.

Is it because it doesn't use multiple interpreters anymore? Or what's the reason?

**Comment by farizrahman4u** [comment]
@saudet exactly: https://github.com/KonduitAI/deeplearning4j/blob/fr_fastpy/datavec/datavec-python/src/main/java/org/datavec/python/PythonContextManager.java#L26

**Pull request closed without merging**
