### PR TITLE
RL4J - Added async training & Advantage Actor Critic

### PR DESCRIPTION
**Pull request by aboulang2002**
## What changes were proposed in this pull request?

In this PR, I add what is required to do async training. I haven't checked too deeply in the rest of DeepLearning4J, but from RL4J's point of view, the async training is done completely lock free. I also adapted A3C to work with the new classes.

I included my test setup (see `AgentLearnerCartpole` in test). This will be more convenient than copy-and-paste test code in the PR description each time. I will remove it in a later PR.
You can change lines 48-50 to configure the sync / async and lines 65-67 to select the algorithm. Note that DQN is not available with async.

This is a big PR; as always, I can split it in multiple PRs if it's easier for you.

## How was this patch tested?

unit tests and manual tests

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X] Created tests for any significant new code additions.
- [X] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by aboulang2002** [comment]
Note: rl4j-core doesn't seem to compile for me, even when I try with master, I get this error:
```
[ERROR] Failed to execute goal on project rl4j-core: Could not resolve dependencies for project org.deeplearning4j:rl4j-core:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:ffmpeg:jar:android-arm:4.3-1.5.4-SNAPSHOT, org.bytedeco:ffmpeg:jar:android-arm64:4.3-1.5.4-SNAPSHOT, org.bytedeco:ffmpeg:jar:android-x86:4.3-1.5.4-SNAPSHOT, org.bytedeco:ffmpeg:jar:android-x86_64:4.3-1.5.4-SNAPSHOT, org.bytedeco:ffmpeg:jar:linux-armhf:4.3-1.5.4-SNAPSHOT, org.bytedeco:ffmpeg:jar:linux-arm64:4.3-1.5.4-SNAPSHOT, org.bytedeco:ffmpeg:jar:linux-ppc64le:4.3-1.5.4-SNAPSHOT, org.bytedeco:ffmpeg:jar:windows-x86:4.3-1.5.4-SNAPSHOT: Could not find artifact org.bytedeco:ffmpeg:jar:android-arm:4.3-1.5.4-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

**Comment by saudet** [comment]
> Note: rl4j-core doesn't seem to compile for me, even when I try with master, I get this error:

Fixed! Thanks for reporting

**Comment by aboulang2002** [comment]
Close PR, then re-open: just a mistake, sorry about it.

**Review by saudet — CHANGES_REQUESTED** [review]
Renaming ACPolicy breaks backward compatibility. Can we leave its name like it was?

**Comment by aboulang2002** [comment]
No problem, renamed ActorCriticPolicy back to what it was.

**Review by saudet — APPROVED** [review]

**Pull request merged**
