### PR TITLE
Add support for CUDA 10.2

### PR DESCRIPTION
**Pull request by saudet**
## What changes were proposed in this pull request?

Update scripts, source code, and documentation to build and run with CUDA 10.2, as well as adjust presets to load new dependencies from libnd4j.

## How was this patch tested?

Builds and runs CUDA examples fine on Fedora 30 from redist artifact.

### CODE REVIEW

**Review by AlexDBlack — COMMENTED** [review]
LGTM, thanks :tada:
I'll report back after testing/building locally and running some tests, just to be sure...

**Review by raver119 — APPROVED** [review]

**Comment by AlexDBlack** [comment]
So, I can build fine using this:
```
libnd4j/buildnativeoperations.sh -c cpu -a avx2 -h mkldnn -j 8 && libnd4j/buildnativeoperations.sh -c cuda -cc 61 -j 8 && mvn clean install -Dmaven.test.skip -Dmaven.javadoc.skip=true -Dlibnd4j.cuda=10.2 -Dlibnd4j.compute=61 -pl '!libnd4j'
```
until I hit this:
https://gist.github.com/AlexDBlack/471dff473d3042c6a03a4fb006f4332f
(downloading snapshots when using shell script build also happens on master)


Whereas if I use maven:
```
mvn install -pl libnd4j -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dlibnd4j.cuda=10.2 -Dlibnd4j.compute=61 && mvn clean install -Dmaven.test.skip -Dmaven.javadoc.skip=true -Dlibnd4j.cuda=10.2 -Dlibnd4j.compute=61 -pl '!libnd4j'
```
I get this:
https://gist.github.com/AlexDBlack/6f82449ae9c74eb5c86d4e3aef693e01

Note the latter command works on master (with 10.1 of course)

**Comment by saudet** [comment]
Looks like the build is assuming something about the state of the artifacts on the CI server...?

**Comment by AlexDBlack** [comment]
For the first issue, I think it's more that the buildnativeoperations.sh script (when not run through maven) doesn't install to the local maven repository, but we still have a dependency on it. So it fetches it from sonatype instead.
Even though we don't actually need the maven copy during the build, as we should (and are, afaik are) using the output of the manually run build script.

**Comment by AlexDBlack** [comment]
So if I cut out most of the args in the pom.xml for CPU build, I get this (using mvn clean install):
https://gist.github.com/AlexDBlack/e9101d0326fc35bf2d01a443dc62ecab
```
[INFO] bash C:\DL4J\Git\deeplearning4j\libnd4j/buildnativeoperations.sh --chip cpu
/bin/bash: C:\DL4J\Git\deeplearning4j\libnd4j/buildnativeoperations.sh: No such file or directory
```
Which doesn't make sense. I've also double checked the PR, everything looks fine to me.

It would be good to know if this is isolated to my machine somehow, or whether it's reproducible elsewhere.

**Comment by raver119** [comment]
You probably have WSL installed. I've fallen into this recently. So, bash cmd executes /bin/bash from WSL rather than mingw

**Comment by AlexDBlack** [comment]
Yep, I definitely do have WSL (WSL 2 in fact) installed, added fairly recently...

**Comment by raver119** [comment]
In this case temporary workaround is trivial. In pom.xml replace `bash` with absolute path to it.

**Review by AlexDBlack — APPROVED** [review]
Bash path issues aside, it seems to build and run OK.
I'm seeing a small number of ND4J test failures (TF import tests) but they could be failing on master also (would need to rebuild and check).

I say we merge this and fix those after.

image

**Comment by raver119** [comment]
These failures are on master atm. 

- check_numerics/strictly_increasing are order of exec issues we've discussed before
- svd is a sign issue. graph should be modified with abs op following svd
- and only mobilenet is something new.

**Pull request merged**
