### PR TITLE
Drop unused profiles for artifacts distribution

### PR DESCRIPTION
**Pull request by sshepel**
## What changes were proposed in this pull request?

Drop unused profiles for artifacts distribution

## How was this patch tested?

Jenkins

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by sshepel** [comment]
Not sure if we need **skymindnexus-skil**, what do you think @AlexDBlack ?

**Comment by AlexDBlack** [comment]
@sshepel 
> Not sure if we need skymindnexus-skil, what do you think @AlexDBlack ?

Yeah, I'm not aware of any reasons we need that... it can be removed also.

**Comment by sshepel** [comment]
> Yeah, I'm not aware of any reasons we need that... it can be removed also.

Done

**Review by AlexDBlack — APPROVED** [review]
Let's merge this then, unless there's any more to do...

**Pull request merged**
