### PR TITLE
Add Maven profiles for ARM builds to pom.xml files

### LINKED ISSUE #8726: Jetson Nano resolves to non existing architecture (linux-aarch64)
#### Issue Description
Builds on jetson nano resolve to wrong javacpp architecture:
Relevant snippet:
```
inkResource>${javacpp.linkResource}</linkResource>                                                                                                                                                                 <linkResources>                                                                                                                                                                                                        <linkResource>/${javacpp.platform.library.path}/</linkResource>                                                                                                                                                      <linkResource>/${javacpp.platform.library.path}/lib/</linkResource>                                                                                                                                                  <linkResource>/org/bytedeco/openblas/linux-aarch64/</linkResource>                                                                                                                                                   <linkResource>/org/bytedeco/openblas/linux-aarch64/lib/</linkResource>${javacpp.linkResources}</linkResources>                                                                                                     <outputDirectory>${javacpp.outputDirectory}</outputDirectory>                                                                                                                                                        <outputName>${javacpp.outputName}</outputName>                                                                                                                                                                       <plugin default-value="${plugin}"/>                                                                                                                                                                                  <preloadPath>${javacpp.preloadPath}</preloadPath>                                                                                                                                                                    <preloadPaths>${javacpp.preloadPaths}</preloadPaths>                                                                                                                                                                 <preloadResource>${javacpp.preloadResource}</preloadResource>                                                                                                                                                        <preloadResources>${javacpp.preloadResources}</preloadResources>                                                                                                                                                     <project default-value="${project}"/>                                                                                                                                                                                <properties>linux-aarch64</properties>                                                                                                                                                                               <propertyFile>${javacpp.propertyFile}</propertyFile>                                                                                                                                                                 <propertyKeysAndValues>                                                                                                                                                                                                <property>                                                                                                                                                                                                             <name>platform.root</name>                                                                                                                                                                                           <value></value>                  
```

The platform appears to be linux-aarch64. We have linux-arm64 in snapshots already.
I imagine we just need an alias?
Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information
SNAPSHOTS
Linux for Tegra on Jetson Nano (based on ubuntu 18.04)

### PR DESCRIPTION
**Pull request by saudet**
## What changes were proposed in this pull request?

Fixes eclipse#8726

## How was this patch tested?

Tested manually with the examples to make sure it doesn't break the build, but not tested on ARM.

### CODE REVIEW

**Comment by agibsonccc** [comment]
@saudet build still fails.
[ERROR] Failed to execute goal on project nd4j-native: Could not resolve dependencies for project org.nd4j:nd4j-native:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:openblas:jar:linux-aarch64:0.3.8-1.5.3-SNAPSHOT, org.bytedeco:mkl:jar:linux-aarch64:2020.0-1.5.3-SNAPSHOT: Could not find artifact org.bytedeco:openblas:jar:linux-aarch64:0.3.8-1.5.3-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)

**Comment by saudet** [comment]
You'll need to install the new parent pom.xml file for the changes to take effect.

**Review by agibsonccc — DISMISSED** [review]
Builds for me now

**Comment by raver119** [comment]
downgrade openblas to 0.3.7 doesn't help us on threadripper, so let's revert this and stay with 0.3.8. We'll solve that problem in other way i think.

**Comment by agibsonccc** [comment]
@raver119 merge this then?

**Pull request merged**
